### ISSUE TITLE
isEmpty() NPE's

### ISSUE THREAD

**Issue by iDznPB** [powbot/api#16]
java.nio.BufferUnderflowException
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:182)
	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:762)
	at org.powerbot.bot.cache.FileContainer.try(FileContainer.java:35)
	at org.powerbot.bot.cache.FileContainer.<init>(FileContainer.java:23)
	at org.powerbot.bot.cache.CacheWorker.getBlock(CacheWorker.java:68)
	at org.powerbot.script.rt4.CacheComponentConfig.load(CacheComponentConfig.java:105)
	at org.powerbot.script.rt4.Widget.<init>(Widget.java:26)
	at org.powerbot.script.rt4.Widgets.widget(Widgets.java:34)
	at org.powerbot.script.rt4.Widgets.get(Widgets.java:67)
	at org.powerbot.script.AbstractQuery.lambda$new$0(AbstractQuery.java:27)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at org.powerbot.script.AbstractQuery.select(AbstractQuery.java:61)
	at org.powerbot.script.rt4.Components.get(Components.java:81)
	at org.powerbot.script.AbstractQuery.lambda$new$0(AbstractQuery.java:27)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at org.powerbot.script.AbstractQuery.select(AbstractQuery.java:74)
	at org.powerbot.script.rt4.Components.select(Components.java:64)
	at org.powerbot.bot.rt4.Login.try(Login.java:48)
	at org.powerbot.bot.rt4.Login.for(Login.java:44)
	at org.powerbot.bot.rt4.Login.poll(Login.java:67)
	at org.powerbot.script.PollingScript$1.run(PollingScript.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
08:24 CacheWorker: your cache is corrupt, please try rebooting the bot client
java.lang.IllegalArgumentException: newPosition > limit: (520 > 6)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
	at java.base/java.nio.Buffer.position(Buffer.java:293)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1086)
	at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:226)
	at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:67)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:279)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:811)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:793)
	at org.powerbot.bot.cache.FileStore.get(FileStore.java:67)
	at org.powerbot.bot.cache.CacheWorker.getBlock(CacheWorker.java:67)
	at org.powerbot.script.rt4.CacheObjectConfig.load(CacheObjectConfig.java:42)
	at org.powerbot.script.rt4.GameObject.id(GameObject.java:86)
	at org.powerbot.script.Identifiable$Matcher.accept(Identifiable.java:77)
	at org.powerbot.script.Identifiable$Matcher.accept(Identifiable.java:68)
	at org.powerbot.script.AbstractQuery.select(AbstractQuery.java:92)
	at org.powerbot.script.rt4.BasicQuery.id(BasicQuery.java:81)
	**at iDzn.ZulrahHelperPro.ZulrahHelperPro.repaint(ZulrahPro.java:375)**
	at org.powerbot.script.PaintEvent.call(PaintEvent.java:54)
	at org.powerbot.bot.rt4.EventDispatcher.try(EventDispatcher.java:130)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.powerbot.bot.rt4.EventDispatcher.try(EventDispatcher.java:73)
	at org.powerbot.bot.EventDispatcher.consume(EventDispatcher.java:38)
	at org.powerbot.bot.rt4.RT4Canvas.getGraphics(RT4Canvas.java:26)
	at be.b(Unknown Source)
	at client.ak(Unknown Source)
	at ba.d(Unknown Source)
	at ba.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
-- another trace
java.lang.NullPointerException
	at org.powerbot.bot.cache.FileContainer.<init>(FileContainer.java:21)
	at org.powerbot.bot.cache.CacheWorker.getBlock(CacheWorker.java:68)
	at org.powerbot.script.rt4.CacheObjectConfig.load(CacheObjectConfig.java:42)
	at org.powerbot.script.rt4.GameObject.id(GameObject.java:86)
	at org.powerbot.script.Identifiable$Matcher.accept(Identifiable.java:77)
	at org.powerbot.script.Identifiable$Matcher.accept(Identifiable.java:68)
	at org.powerbot.script.AbstractQuery.select(AbstractQuery.java:92)
	at org.powerbot.script.rt4.BasicQuery.id(BasicQuery.java:81)
	at iDzn.ZulrahPro.ZulrahPro.repaint(ZulrahPro.java:375)
	at org.powerbot.script.PaintEvent.call(PaintEvent.java:54)
	at org.powerbot.bot.rt4.EventDispatcher.try(EventDispatcher.java:130)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.powerbot.bot.rt4.EventDispatcher.try(EventDispatcher.java:73)
	at org.powerbot.bot.EventDispatcher.consume(EventDispatcher.java:38)
	at org.powerbot.bot.rt4.RT4Canvas.getGraphics(RT4Canvas.java:26)
	at be.b(Unknown Source)
	at client.ak(Unknown Source)
	at ba.d(Unknown Source)
	at ba.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)

**at iDzn.ZulrahHelperPro.ZulrahHelperPro.repaint(ZulrahHelperPro.java:375)** This line here is referring to the following:
**_ctx.objects.select(20).id(c.pillarID).isEmpty()_**
Afaik, this is a boolean, true if count of the items in the query = 0, false otherwise. Slowly started to see this issue more and more over the last few days, restarting the client usually fixes it. However not sure why it's returning an npe instead of just false..

Now it's every time it's run without fail. _Rick suggested it was my cache, I deleted the cache, relogged in to the client and then reloaded the client again and still the same problem.

**Comment by rvbiljouw** [comment]
this seems specific to cache and might be solved by the most recent update. would be helpful if you can confirm.
